config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
  root controller: :rooms, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, inverse_of: :messages
  belongs_to :room, inverse_of: :messages
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages, dependent: :destroy
	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!

  def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  	@rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @json_object = RoomsSerializer.new(@room).as_json
  end

  def new
  	@room = Room.new
  end

  def create
  	@room = current_user.rooms.new(room_params)
  	if @room.save
      flash[:success] = 'Chat room sucessfully created.'
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  private
  	def room_params
      params.require(:room).permit(:name)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat Web App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <p class="navbar-text float-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.haml
%h2.text-center
  Chat rooms
  %br
  %small
    = link_to 'New chat room', new_room_path, class: 'btn btn-primary btn-sx'

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Owner
      %th Created At
      %th
  %tbody
    - @rooms.each do |chat_room|
      %tr
        %td
          = chat_room.name
        %td
          = chat_room.user.username
        %td
          = chat_room.created_at
        %td
          = link_to "Enter", room_path(chat_room), class: "btn btn-sm btn-primary"

app/views/rooms/new.html.haml
%h2.text-center
  Create Chat Room
  %br
  %small
    = link_to 'Back', rooms_path, class: 'btn btn-primary btn-sx'
    
= form_for @room do |f|
  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: 'form-control'

  = f.submit "Save", class: 'btn btn-primary'

app/views/rooms/show.html.haml
%h2.text-center
  = @room.name
  %br
  %small
    = link_to 'Back', rooms_path, class: 'btn btn-primary btn-sx'

= react_component('Room', { room: @json_object })